---
title: "R Notebook"
output: html_notebook
---



```{r}
#this codes makes the analysis for the netwrks

library(ggplot2)
library(dplyr)
library(tidyverse)
library(igraph)
library(reshape2)

mycols <- c("#021128","#1b4a64", "#3585a0", "#759580", "#c78f34", "#fd9706","#fdb81c","#fbdb30")
mycols3a <-c("#021128", "#fd9706", "#1b4a64", "#759580")
mycols3b <-c("#1b4a64", "#fdb81c", "#759580")
mycols3c <- c("#759580", "#1b4a64","#fdb81c")
groupColors2 <- c("#1b4a64", "#fd9706", "#fbdb30", "white")#ESTE ES CEMTAL
colorRedes <- c("black", "black","darkred")
```

```{r}
rerunAna <- 0

if (rerunAna == 1){

DF_TOTAL <- read.csv("../../data/DF_total_TF.csv", header = TRUE)

DF_TOTAL <- DF_TOTAL %>% 
  filter(porcionCosecha != "S_F")


#remove unuses colunmns
DF_TOTAL$X.1 <- NULL
DF_TOTAL$FruitLoad <- NULL
DF_TOTAL$TotalHarvest <- NULL


###########this is to see the new infection by harvest########333
DF_NEW<-  DF_TOTAL%>%
  group_by(X, Y, Rep, numPlants)%>% #son las vairables que quedan y sobre esos escenarios, vamos a hacer las diferencias entre modelos
  summarise(NUEVA_RUST = (Rust - Rust[HarvestModel=="control"]), 
            porcionCosecha = porcionCosecha
            )%>%
  filter(porcionCosecha != 1)%>% #para quitar las lineas del control
  filter(NUEVA_RUST ==1)


#esto sirve para correr pruebas puntuales

nP =2000
rP = 0
pC = "A"


#columns = c("Rep", "numPlants",  "porcionCosecha",  "N_REDES",  "T_REDES" , "MAX_T_REDES") 
columns = c("Rep", "numPlants",  "porcionCosecha") 

DF_HIST = data.frame() 

  for (nP in unique(DF_NEW$numPlants)){
    for (pC in unique(DF_NEW$porcionCosecha)) {
      #contador <- 0
      for (rP in unique(DF_NEW$Rep)) {
      print(c(nP, rP, pC))
      DF_TEMP <- DF_NEW %>%
      filter(numPlants ==nP & Rep == rP & porcionCosecha== pC)
        if (nrow(DF_TEMP)==0){  #esto porque hay comb que no exiten en las nuevas redes
    }
        else
    {  
          N <- dim(DF_TEMP)[1]
  
          distance_matrix <- matrix(0,nrow=N,ncol=N)
          for( i in 1:N){
            for( j in 1:N ){
              distance_matrix[i,j] <- sqrt( (DF_TEMP$X[i] - DF_TEMP$X[j])^2 + (DF_TEMP$Y[i] - DF_TEMP$Y[j])^2 )
        #image(distance_matrix)
        }
    }
    
          Crit_Dist <- 1.5
    
    #MAKE ADJ MATRIX WITH CRITICAL DISTANCE
          adj_matrix <- matrix(0,nrow=N,ncol=N)
    
          for(i in 1:N){
            for(j in 1:N){
              if(i != j & distance_matrix[i,j] <= Crit_Dist){
                adj_matrix[i,j] = 1
                }else{
                  adj_matrix[i,j] = 0
        }
      }
    }
   #image(adj_matrix)
    plot_graph <- graph.adjacency(adj_matrix,mode="undirected")
    #Pull out cluster IDs and put them in the data set
    
    zippin <-layout.fruchterman.reingold(plot_graph)
    zippin[,1] <- DF_TEMP$X
    zippin[,2] <- DF_TEMP$Y
    
    groups <- unlist(clusters(plot_graph)[1])
    DF_TEMP$cluster <- groups
    #Add degree to our data set too
    
    
    
    DF_TEMP$CONTEO <- 1
    #aqui saque el grado a mano
    DF_TEMP <- DF_TEMP %>%
      group_by(Rep, numPlants, NUEVA_RUST, porcionCosecha, cluster)%>%
      summarise(degree = sum(CONTEO)) 
    
    
    ###now we gonna count how many per sizeof cluster per reptition
    
    DF_TEMP$CONTEO2 <- 1
    DF_TEMP_HIS <- DF_TEMP  %>%
      group_by(Rep, numPlants, porcionCosecha, degree)%>%
      summarise(frecDegree = sum(CONTEO2))
    
    DF_HIST <- rbind(DF_HIST, DF_TEMP_HIS)

    }
  }
    }
  }






write.csv(DF_HIST, "../../data/histHar.csv")


}

```


```{r}
DF_HIST <- read.csv("../../data/histHar.csv", header = TRUE)

DF_HIST$plantRust <- DF_HIST$degree * DF_HIST$frecDegree
DF_HIST$perPlantRust <- 100*DF_HIST$plantRust/DF_HIST$numPlants
```

```{r}

DF_HIST<- DF_HIST%>%
  ungroup() %>%
  group_by(Rep, numPlants, porcionCosecha) %>%
  mutate(plantCUM = cumsum(perPlantRust))

FIG_ALL_REP <- DF_HIST %>%
  ggplot(aes(x = degree)) +
  geom_line(aes(y = plantCUM, color = factor(Rep)), linewidth = 1)+
  # Faceting
  facet_grid(porcionCosecha~numPlants) +
  scale_color_viridis_d()+
  # Theme and labels
  theme_bw() +
  theme(
    text = element_text(size = 25),
    #legend.position = "none",
    strip.background = element_rect(fill = "white")
  )

```



```{r}
DF_HIST_HAR <- DF_HIST %>%
  ungroup() %>%
  group_by(numPlants, porcionCosecha, degree) %>%
  summarise(meanFrecDeg = mean(frecDegree), sdFrecDeg = sd(frecDegree), 
            meanPlantCUM = mean(plantCUM), sdPlantCUM = sd(plantCUM))



DF_HIST_HAR$porcionCosecha[DF_HIST_HAR$porcionCosecha =="A"] <- "Asynchronous"
#DF_POST_RES$porcionCosecha[DF_POST_RES$porcionCosecha =="S_F"] <- "Synchronous Final" 
DF_HIST_HAR$porcionCosecha[DF_HIST_HAR$porcionCosecha =="S_I"] <- "Synchronous"
```


```{r}
FIG_HIST_HAR <- DF_HIST_HAR %>%
  ggplot(aes(x = degree)) +
  # Primary y-axis: meanFrecDeg (bars)
  geom_col(aes(y = meanFrecDeg, 
               fill = as.factor(numPlants),
               color= as.factor(numPlants)), 
           position = "dodge",
           width = 1,
           alpha=0.7) +
scale_fill_viridis_d(option = "inferno", direction = -1, end = 0.8)  +
  scale_color_viridis_d(option = "inferno", direction = -1, end = 0.8)  +

  # Faceting
  facet_wrap(~porcionCosecha, ncol = 1) +
  
  # Theme and labels
  theme_bw() +
  theme(
    text = element_text(size = 25),
    legend.position = "none",
    strip.background = element_rect(fill = "white")
  ) +
  labs(
    fill = "", 
    col = "",
    x = bquote("Size of network"), 
    y = "Average number of infected networks AH"
  ) 


ggsave(FIG_HIST_HAR,filename=paste("../../output/graficas/SUP_FIG/", "NetHar.png", sep=""),  height = 10, width = 12) # ID will be the unique identifier. and change the extension from .png to whatever you like (eps, pdf etc).
```


```{r}

FIG_CUM_HAR <- DF_HIST_HAR %>%
  ggplot(aes(x = degree)) +
  # Primary y-axis: meanFrecDeg (bars)
  
  geom_line(aes(y = meanPlantCUM, color = factor(numPlants)), linewidth = 1) +
  geom_ribbon(aes(ymin = meanPlantCUM - sdPlantCUM, ymax = meanPlantCUM + sdPlantCUM, fill = factor(numPlants)), alpha = 0.5) +
 

scale_fill_viridis_d(option = "inferno", direction = -1, end = 0.8)  +
scale_color_viridis_d(option = "inferno", direction = -1, end = 0.8)  +

  # Faceting
  facet_wrap(~porcionCosecha, ncol = 1) +
  # Theme and labels
  theme_bw() +
  theme(
    text = element_text(size = 25),
    #legend.position = "none",
    strip.background = element_rect(fill = "white")
  ) +
  labs(
    fill = "Density (Plants/ha)", 
    color=  "Density (Plants/ha)",
    x = bquote("Size of network"), 
    y = "Cumulative percentage of infected plants AH"
  ) 


ggsave(FIG_CUM_HAR,filename=paste("../../output/graficas/SUP_FIG/", "CumHar.png", sep=""),  height = 10, width = 10) # ID will be the unique identifier. and change the extension from .png to whatever you like (eps, pdf etc).



```

